server:
  port: 8090

# 驱动配置信息
spring:
  datasource:
    druid:
      one:
        driverClassName : com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/master_dev_1?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: lyy@hotmail.com
        min-idle: 3
        initial-size: 3
        max-active: 10
        max-wait: 60000
#        filter:
#          stat:
#            log-slow-sql: true
#            slow-sql-millis: 2000
#        stat-view-servlet:
#          login-username: admin
#          login-password: 123123
      two:
        driverClassName : com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/master_dev_2?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: lyy@hotmail.com
        max-active: 30
        max-wait: 10000
        min-idle: 3
        initial-size: 3
#        filter:
#          stat:
#            log-slow-sql: true
#            slow-sql-millis: 2000
#        stat-view-servlet:
#          login-username: admin
#          login-password: 123123
#      stat-view-servlet:
#      filter:
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 2000
#      stat-view-servlet:
#        login-username: admin
#        login-password: 123123
#配置实体路径
mybatis:
  type-aliases-package: com.liyingyu.multidatasource.entity




